stages:
  - dockit
  - data-verification
  
matrix:
  include:
        - stage: dockit
          language: c
          services: 
            - docker
          script: 
            - docker pull pnwairfire/bluesky-framework
            #bluesky binary is not at root of image, hence long path
            - docker run pnwairfire/bluesky-framework /bluesky/dist/bluesky/./bluesky -h -h

        - stage: data-verification
          language: python
          python: 
            - "3.7"
          install:
            - pip install pandas
          script:
            - cd test/mvp-output
            - python3 test.py