stages:
  - dockit
  
matrix:
  include:
      - stage: dockit
        language: c
        services: 
          - docker
        script: 
          - docker run hello-world
          - docker ps
          - echo "end of multiline script"
