stages:
  - dockit
  
matrix:
  include:
        - stage: dockit
          language: c
          services: 
            - docker
          script: 
            - docker pull pnwairfire/bluesky
            - docker run pnwairfire/bluesky bsp -h
            - echo "end of multiline script"