stages:
  - buildpy
  - buildc
  - dockit

matrix:
  include:
      - stage: buildpy
        language: python
        script: python3 hello.py

      - stage: buildc
        language: c
        script: gcc hello_world.c
      
      - stage: dockit
        language: c
        services: 
          - docker
        script: docker run hello-world
